Respuestas Parciales
================

# Quiénes somos

El [Club de R para RRHH](https://r4hr.club) es una comunidad de
aprendizaje de programación en R destinada para las personas que
trabajan en Recursos Humanos en países de habla hispana.

Nuestro objetivo es acercar el mundo de ciencias de datos a nuestra
profesión, adaptando el contenido a nuestros skills y conocimientos, y
también siempre que podemos, usando datos relacionados con la gestión de
personas, y en castellano, para hacer más accesible el aprendizaje.

Este es un proyecto que ideó [Sergio García
Mora](https://www.linkedin.com/in/sergiogarciamora/), y que reúne a
gente de Argentina, Perú, Chile, Paraguay, Uruguay, Panamá, USA,
Francia, y cada vez más y más profesionales de distintas latitudes se
unen y contribuyen al proyecto.

Para más información sobre el Club de R leé [este
post](https://r4hr.club/2020/09/23/el-club-de-r-para-rrhh/), o
escribinos a <info@r4hr.club>.

## La encuesta KIWI 🥝 de Sueldos de RRHH para LATAM

Uno de los problemas en el aprendizaje de People Analytics es la falta
de datasets para practicar, así que una decisión que tomamos fue el de
generar nuestro propio dataset y de abrirlo para toda la comunidad.

Para hacer esta encuesta nos “inspiramos” en
[SysArmy](https://sysarmy.com/blog/), una comunidad para las personas
que trabajan en tecnología que además de organizar uno de los eventos
más importantes de tecnología de Argentina, Nerdearla, y también
organizan una encuesta salarial dos veces por año.

Estas son las motivaciones detrás de esta encuesta. Tener nuestro propio
dataset, compartir los resultados y los datos, para que todos los
entusiastas de RRHH y los datos cuenten con una fuente de datos para
practicar.

> Si querés conocer la historia detrás del nombre de la encuesta, la
> podés [conocer aquí](https://r4hr.club/why-kiwi/).

## Organizadores

🕵 [Adrián Quiroga](https://www.linkedin.com/in/adrian-quiroga-ab57424b/)

👩‍💻 [Alithu Castro](https://www.linkedin.com/in/alithucastro/)

👩‍🎓 [Andrea Herpsomer](https://www.linkedin.com/in/andreaherpsomer/)

👩‍🎨 [Carla Cirone](https://www.linkedin.com/in/carla-cirone-0566b095/)

👩‍💻 [Daniela
García](https://www.linkedin.com/in/claudia-daniela-garcia-138b1a14b/)

👩‍🚀 [Lucía Huilén
Gómez](https://www.linkedin.com/in/luc%C3%ADa-huil%C3%A9n-g%C3%B3mez-93565276/)

👨‍🎤 [Santiago Lardone
Quinodoz](https://www.linkedin.com/in/santiago-lardone-quinodoz-978588167/)

🐍 [Sebastián
Lombraña](https://www.linkedin.com/in/santiago-lardone-quinodoz-978588167/)

🤘 [Sergio García Mora](https://www.linkedin.com/in/sergiogarciamora/)

👩‍🏫 [Yanel Paulette](https://www.linkedin.com/in/yanelpaulette/)

# Respuestas parciales

<img src="https://media.giphy.com/media/xThtalkAxYnZd94uB2/giphy.gif"/>

El 12 de noviembre publicamos los resultados finales.

# Participación

## Respuestas por países

<!--html_preserve-->

<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#dgihmfbysk .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#dgihmfbysk .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#dgihmfbysk .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#dgihmfbysk .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#dgihmfbysk .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#dgihmfbysk .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#dgihmfbysk .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#dgihmfbysk .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#dgihmfbysk .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#dgihmfbysk .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#dgihmfbysk .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#dgihmfbysk .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#dgihmfbysk .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#dgihmfbysk .gt_from_md > :first-child {
  margin-top: 0;
}

#dgihmfbysk .gt_from_md > :last-child {
  margin-bottom: 0;
}

#dgihmfbysk .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#dgihmfbysk .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#dgihmfbysk .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#dgihmfbysk .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#dgihmfbysk .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#dgihmfbysk .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#dgihmfbysk .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#dgihmfbysk .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#dgihmfbysk .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#dgihmfbysk .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#dgihmfbysk .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#dgihmfbysk .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#dgihmfbysk .gt_left {
  text-align: left;
}

#dgihmfbysk .gt_center {
  text-align: center;
}

#dgihmfbysk .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#dgihmfbysk .gt_font_normal {
  font-weight: normal;
}

#dgihmfbysk .gt_font_bold {
  font-weight: bold;
}

#dgihmfbysk .gt_font_italic {
  font-style: italic;
}

#dgihmfbysk .gt_super {
  font-size: 65%;
}

#dgihmfbysk .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>

<div id="dgihmfbysk" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_header">

<tr>

<th colspan="2" class="gt_heading gt_title gt_font_normal" style>

Cantidad de respuestas por país

</th>

</tr>

<tr>

<th colspan="2" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>

Países con más de 5 respuestas

</th>

</tr>

</thead>

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">

País en el que trabajas

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">

Cuenta

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_left">

Argentina

</td>

<td class="gt_row gt_right">

572

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Bolivia

</td>

<td class="gt_row gt_right">

12

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Chile

</td>

<td class="gt_row gt_right">

12

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Paraguay

</td>

<td class="gt_row gt_right">

12

</td>

</tr>

<tr>

<td class="gt_row gt_left">

México

</td>

<td class="gt_row gt_right">

8

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Uruguay

</td>

<td class="gt_row gt_right">

8

</td>

</tr>

<tr>

<td class="gt_row gt_left">

Perú

</td>

<td class="gt_row gt_right">

5

</td>

</tr>

</tbody>

</table>

</div>

<!--/html_preserve-->

Recibimos un total de 641 respuestas 🎉:trophy:.

# Comparación de sueldos de RRHH por países

![](respuestas_parciales_files/figure-gfm/sueldos_dolar-1.png)<!-- -->

**Aclaraciones:**

1.  Los resultados no son representativos dada la baja cantidad de
    respuestas (cada punto representa una respuesta).
2.  Para la comparación de los sueldos en dólares estadounidenses
    tomamos el tipo de cambio de cada país al 19 de octubre de 2020
    publicados por los respectivos bancos centrales.
3.  Sólo mostramos resultados de los países con al menos 5 respuestas.
4.  Podamos los sueldos para mostrar aquellos que están dentro de los
    percentiles 5 y 95.

# Representación de mujeres en puestos de liderazgo

## Participación según género

<img src="respuestas_parciales_files/figure-gfm/respuestas-genero-1.png" width="90%" />

<!--html_preserve-->

<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#zxuybdqxxg .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#zxuybdqxxg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zxuybdqxxg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#zxuybdqxxg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 4px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#zxuybdqxxg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zxuybdqxxg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zxuybdqxxg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#zxuybdqxxg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#zxuybdqxxg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#zxuybdqxxg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#zxuybdqxxg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#zxuybdqxxg .gt_group_heading {
  padding: 8px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#zxuybdqxxg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#zxuybdqxxg .gt_from_md > :first-child {
  margin-top: 0;
}

#zxuybdqxxg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#zxuybdqxxg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#zxuybdqxxg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 12px;
}

#zxuybdqxxg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zxuybdqxxg .gt_first_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
}

#zxuybdqxxg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zxuybdqxxg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#zxuybdqxxg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#zxuybdqxxg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zxuybdqxxg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zxuybdqxxg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding: 4px;
}

#zxuybdqxxg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zxuybdqxxg .gt_sourcenote {
  font-size: 90%;
  padding: 4px;
}

#zxuybdqxxg .gt_left {
  text-align: left;
}

#zxuybdqxxg .gt_center {
  text-align: center;
}

#zxuybdqxxg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#zxuybdqxxg .gt_font_normal {
  font-weight: normal;
}

#zxuybdqxxg .gt_font_bold {
  font-weight: bold;
}

#zxuybdqxxg .gt_font_italic {
  font-style: italic;
}

#zxuybdqxxg .gt_super {
  font-size: 65%;
}

#zxuybdqxxg .gt_footnote_marks {
  font-style: italic;
  font-size: 65%;
}
</style>

<div id="zxuybdqxxg" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">

<table class="gt_table">

<thead class="gt_header">

<tr>

<th colspan="3" class="gt_heading gt_title gt_font_normal" style>

Cantidad de respuestas según género

</th>

</tr>

<tr>

<th colspan="3" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>

</th>

</tr>

</thead>

<thead class="gt_col_headings">

<tr>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Género

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Cantidad

</th>

<th class="gt_col_heading gt_columns_bottom_border gt_center" rowspan="1" colspan="1">

Porcentaje

</th>

</tr>

</thead>

<tbody class="gt_table_body">

<tr>

<td class="gt_row gt_center">

Femenino

</td>

<td class="gt_row gt_center">

380

</td>

<td class="gt_row gt_center">

66.9%

</td>

</tr>

<tr>

<td class="gt_row gt_center">

Masculino

</td>

<td class="gt_row gt_center">

185

</td>

<td class="gt_row gt_center">

32.6%

</td>

</tr>

<tr>

<td class="gt_row gt_center">

No binario

</td>

<td class="gt_row gt_center">

2

</td>

<td class="gt_row gt_center">

0.4%

</td>

</tr>

<tr>

<td class="gt_row gt_center">

Prefiero no responder

</td>

<td class="gt_row gt_center">

1

</td>

<td class="gt_row gt_center">

0.2%

</td>

</tr>

</tbody>

<tfoot class="gt_sourcenotes">

<tr>

<td class="gt_sourcenote" colspan="3">

Fuente: Encuesta KIWI de Sueldos de RRHH para Latam

</td>

</tr>

</tfoot>

</table>

</div>

<!--/html_preserve-->

## Participación según género

De acuerdo a las respuestas recolectadas **2 de cada 3** participantes
son mujeres.

Para los puestos de liderazgo consideramos las personas en los puestos
de *Director, Gerente, Jefe, Responsable,* y *Supervisor*.

Del total de mujeres, 380 respuestas, 163 ocupan un puesto de liderazgo
(42.9%).

Del total de hombres, 185 respuestas, 94 ocupan un puesto de liderazgo
(50.8%).

![](respuestas_parciales_files/figure-gfm/genero-lideres-plot-1.png)<!-- -->
